# Generated by Django 5.0.3 on 2024-03-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_shoppingcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='users_who_like_it',
            new_name='is_in_shopping_cart',
        ),
    ]
