# Generated by Django 5.0.3 on 2024-03-12 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_users_who_like_it_recipe_is_in_shopping_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
        migrations.AddField(
            model_name='recipe',
            name='users_who_add_it_shopping_cart',
            field=models.ManyToManyField(related_name='users_shopping_cart', through='recipes.ShoppingCart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='users_who_like_it',
            field=models.ManyToManyField(related_name='users_who_like_it', through='recipes.UsersRecipesFavorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
