# Generated by Django 5.0.3 on 2024-03-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_is_in_shopping_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='users_who_add_it_shopping_cart',
            new_name='is_in_shopping_cart',
        ),
    ]
