# Generated by Django 5.0.3 on 2024-03-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_owner_shoppingcart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='users_who_like_it',
            new_name='is_favorited',
        ),
    ]
